[package]
org = "choreo"
name = "mediation.add_header"
version = "0.1.0"
distribution = "2201.1.0"
keywords=["choreo-apim-mediation-policy"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "choreo"
name = "mediation"
version = "0.4.0"
