[package]
org = "choreo"
name = "mediation.rewrite_resource_path"
version = "0.2.0"
distribution = "2201.1.0"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-inflow"]

[build-options]
observabilityIncluded = true
