[package]
org = "choreo"
name = "mediation.json_to_xml"
version = "0.2.0"
distribution = "2201.1.0"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-inflow", "choreo-apim-mediation-outflow"]

[build-options]
observabilityIncluded = true
